config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import (HomeView, MainPageView, MessageListView, MessageDetailsView, MessageCreateView,
                           MessageUpdateView, MessageDeleteView, MailingListView, MailingCreateView, MailingDetailsView,
                           MailingUpdateView, MailingDeleteView, RecipientListView, RecipientDetailsView,
                           RecipientCreateView, RecipientUpdateView, RecipientDeleteView, MessageInfoView,
                           MailingInfoView, RecipientInfoView, MailingAttemptsListView, finish_mailing, sending_mail,
                           ReportInfoView)

app_name = MailingConfig.name

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("main/", MainPageView.as_view(), name="main"),
    path("message_info/", MessageInfoView.as_view(), name="message_info"),
    path("mailing_info/", MailingInfoView.as_view(), name="mailing_info"),
    path("recipient_info/", RecipientInfoView.as_view(), name="recipient_info"),
    path("report_info/", ReportInfoView.as_view(), name="report_info"),
    path('message_list/', cache_page(60)(MessageListView.as_view()), name='message_list'),
    path("message/create/", MessageCreateView.as_view(), name="message_create"),
    path('message/<int:pk>/', MessageDetailsView.as_view(), name='message_detail'),
    path("message/<int:pk>/update/", MessageUpdateView.as_view(), name="message_update"),
    path("message/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"),
    path('mailing_list/', cache_page(60)(MailingListView.as_view()), name='mailing_list'),
    path("mailing/create/", MailingCreateView.as_view(), name="mailing_create"),
    path('mailing/<int:pk>/', MailingDetailsView.as_view(), name='mailing_detail'),
    path("mailing/<int:pk>/update/", MailingUpdateView.as_view(), name="mailing_update"),
    path("mailing/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"),
    path('recipient_list/', cache_page(60)(RecipientListView.as_view()), name='recipient_list'),
    path("recipient/create/", RecipientCreateView.as_view(), name="recipient_create"),
    path('recipient/<int:pk>/', RecipientDetailsView.as_view(), name='recipient_detail'),
    path("recipient/<int:pk>/update/", RecipientUpdateView.as_view(), name="recipient_update"),
    path("recipient/<int:pk>/delete/", RecipientDeleteView.as_view(), name="recipient_delete"),
    path("mailing_attempts/", MailingAttemptsListView.as_view(), name="mailing_attempts_list"),
    path("finish_mailing/<int:pk>/", finish_mailing, name="finish_mailing"),
    path("send_mail/<int:pk>/", sending_mail, name="send_mail"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.views import (UserRegisterView,  UserInfoView, UserListView, UserDetailsView, UserUpdateView, BlockUserView,
                         UnblockUserView, email_verification, UserForgotPasswordView, UserPasswordResetConfirmView)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="mailing:home"), name="logout"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("user_info/", UserInfoView.as_view(), name="user_info"),
    path("user_list/", cache_page(60)(UserListView.as_view()), name="user_list"),
    path("user/<int:pk>/", UserDetailsView.as_view(), name="user_detail"),
    path("user/<int:pk>/update/", UserUpdateView.as_view(), name="user_update"),
    path("user/<int:pk>/block/", BlockUserView.as_view(), name="user_block"),
    path("user/<int:pk>/unblock/", UnblockUserView.as_view(), name="user_unblock"),
    path("email_confirm/<str:token>/", email_verification, name="email_verification"),
    path("password_reset/", UserForgotPasswordView.as_view(), name="password_reset"),
    path("set_new_password/<uidb64>/<token>/", UserPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
]

mailing/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Mailing, Message, Recipient


class RecipientForm(forms.ModelForm):
    class Meta:
        model = Recipient
        fields = ("email", "first_name", "last_name", "comment")

    def __init__(self, *args, **kwargs):
        super(RecipientForm, self).__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите адрес электронной почты"}
        )
        self.fields["first_name"].widget.attrs.update({"class": "form-control", "placeholder": "Введите имя"})
        self.fields["last_name"].widget.attrs.update({"class": "form-control", "placeholder": "Введите фамилию"})
        self.fields["comment"].widget.attrs.update({"class": "form-control", "placeholder": "Введите комментарий"})

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if Recipient.objects.filter(email=email).exists():
            raise ValidationError("Такой адрес электронной почты уже существует в БД!")
        return email


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ("topic", "text")

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields["topic"].widget.attrs.update({"class": "form-control", "placeholder": "Введите тему сообщения"})
        self.fields["text"].widget.attrs.update({"class": "form-control", "placeholder": "Введите текст сообщения"})


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ("mailing_name", "start_sending", "end_sending", "status", "message", "recipients")

    def __init__(self, *args, **kwargs):
        super(MailingForm, self).__init__(*args, **kwargs)
        self.fields["mailing_name"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите название рассылки"}
        )
        self.fields["start_sending"].widget.attrs.update({"class": "form-control", "type": "datetime-local"})
        self.fields["end_sending"].widget.attrs.update({"class": "form-control", "type": "datetime-local"})
        self.fields["status"].widget.attrs.update({"class": "form-control"})
        self.fields["message"].widget.attrs.update({"class": "form-control"})
        self.fields["recipients"].widget.attrs.update({"class": "form-control"})

mailing/views.py
from datetime import datetime

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail
from django.http import HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from mailing.forms import MessageForm, MailingForm, RecipientForm
from mailing.models import Recipient, Mailing, Message, MailingAttempts
from mailing.services import get_recipient_list, get_message_list, get_mailing_list, get_mailing_attempts_list


class HomeView(TemplateView):
    template_name = "mailing/home.html"


class MessageInfoView(TemplateView):
    template_name = "mailing/message_info.html"


class MailingInfoView(TemplateView):
    template_name = "mailing/mailing_info.html"


class RecipientInfoView(TemplateView):
    template_name = "mailing/recipient_info.html"


class ReportInfoView(TemplateView):
    template_name = "mailing/report_info.html"


class MainPageView(TemplateView):
    """Контроллер отображения отчета."""
    models = [Recipient, Mailing, Message]
    template_name = "mailing/main.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["message_all"] = Message.objects.all()
        context["recipients_all"] = Recipient.objects.all()
        context["mailing_all"] = Mailing.objects.all()
        context["mailing_active"] = Mailing.objects.filter(status=Mailing.ACTIVE)
        return context


class MessageListView(LoginRequiredMixin, ListView):
    """Контроллер отображения списка сообщений."""
    model = Message
    template_name = "mailing/message_list.html"

    def get_queryset(self):
        if self.request.user.has_perm("mailing.view_message"):
            return get_message_list()
        return get_message_list().filter(owner=self.request.user)


class MessageDetailsView(LoginRequiredMixin, DetailView):
    """Контроллер отображения подробностей о сообщении."""
    model = Message
    template_name = "mailing/message_detail.html"


class MessageCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания сообщения."""
    model = Message
    form_class = MessageForm
    template_name = "mailing/message_form.html"
    success_url = reverse_lazy("mailing:message_list")

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Контроллер изменения сообщения."""
    model = Message
    form_class = MessageForm
    template_name = "mailing/message_form.html"
    success_url = reverse_lazy("mailing:message_list")

    def test_func(self):
        recipient = self.get_object()
        return self.request.user == recipient.owner

    def handle_no_permissions(self):
        return HttpResponseForbidden("У вас нет прав на это действие.")

    def get_success_url(self):
        return reverse_lazy("mailing:message_detail", kwargs={"pk": self.object.pk})


class MessageDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Контроллер удаления сообщения."""
    model = Message
    template_name = "mailing/message_confirm_delete.html"
    success_url = reverse_lazy("mailing:message_list")

    def test_func(self):
        recipient = self.get_object()
        return self.request.user == recipient.owner

    def handle_no_permissions(self):
        return HttpResponseForbidden("У вас нет прав на это действие.")


class MailingListView(LoginRequiredMixin, ListView):
    """Контроллер отображения списка рассылок."""
    model = Mailing
    template_name = "mailing/mailing_list.html"

    def get_queryset(self):
        if self.request.user.has_perm("mailing.view_mailing"):
            return get_mailing_list()
        return get_mailing_list().filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailing = self.get_queryset()
        context["mailing_created"] = mailing.filter(status=Mailing.CREATED)
        context["mailing_active"] = mailing.filter(status=Mailing.ACTIVE)
        context["mailing_finished"] = mailing.filter(status=Mailing.FINISHED)
        return context


class MailingDetailsView(LoginRequiredMixin, DetailView):
    """Контроллер отображения подробностей о рассылке."""
    model = Mailing
    template_name = "mailing/mailing_detail.html"


class MailingCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания рассылки."""
    model = Mailing
    form_class = MailingForm
    template_name = "mailing/mailing_form.html"
    success_url = reverse_lazy("mailing:mailing_list")

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Контроллер изменения рассылки."""
    model = Mailing
    form_class = MailingForm
    template_name = "mailing/mailing_form.html"
    success_url = reverse_lazy("mailing:mailing_list")

    def test_func(self):
        recipient = self.get_object()
        return self.request.user == recipient.owner

    def handle_no_permissions(self):
        return HttpResponseForbidden("У вас нет прав на это действие.")

    def get_success_url(self):
        return reverse_lazy("mailing:mailing_detail", kwargs={"pk": self.object.pk})


class MailingDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Контроллер удаления рассылки."""
    model = Mailing
    template_name = "mailing/mailing_confirm_delete.html"
    success_url = reverse_lazy("mailing:mailing_list")

    def test_func(self):
        recipient = self.get_object()
        return self.request.user == recipient.owner

    def handle_no_permissions(self):
        return HttpResponseForbidden("У вас нет прав на это действие.")


class MailingAttemptsListView(LoginRequiredMixin, ListView):
    """Контроллер отображения списка попыток отправки."""
    model = MailingAttempts
    template_name = "mailing/mailing_attempts_list.html"

    def get_queryset(self):
        if self.request.user.has_perm("mailing.view_mailing_attempts"):
            return get_mailing_attempts_list()
        return get_mailing_attempts_list().filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        attempt = self.get_queryset()
        context["success"] = attempt.filter(attempt_status="успешно").count()
        context["failure"] = attempt.filter(attempt_status="не успешно").count()
        context["total"] = attempt.count()
        return context


class RecipientListView(LoginRequiredMixin, ListView):
    """Контроллер отображения списка получателей."""
    model = Recipient
    template_name = "mailing/recipient_list.html"

    def get_queryset(self):
        if self.request.user.has_perm("mailing.view_recipient"):
            return get_recipient_list()
        return get_recipient_list().filter(owner=self.request.user)


class RecipientDetailsView(LoginRequiredMixin, DetailView):
    """Контроллер отображения подробностей о получателе."""
    model = Recipient
    template_name = "mailing/recipient_detail.html"


class RecipientCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания получателя."""
    model = Recipient
    form_class = RecipientForm
    template_name = "mailing/recipient_form.html"
    success_url = reverse_lazy("mailing:recipient_list")

    def form_valid(self, form):
        recipient = form.save()
        user = self.request.user
        recipient.owner = user
        recipient.save()
        return super().form_valid(form)


class RecipientUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Контроллер изменения получателя."""
    model = Recipient
    form_class = RecipientForm
    template_name = "mailing/recipient_form.html"
    success_url = reverse_lazy("mailing:recipient_list")

    def test_func(self):
        recipient = self.get_object()
        return self.request.user == recipient.owner

    def handle_no_permissions(self):
        return HttpResponseForbidden("У вас нет прав на это действие.")

    def get_success_url(self):
        return reverse_lazy("mailing:recipient_detail", kwargs={"pk": self.object.pk})


class RecipientDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Контроллер удаления получателя."""
    model = Recipient
    template_name = "mailing/recipient_confirm_delete.html"
    success_url = reverse_lazy("mailing:recipient_list")

    def test_func(self):
        recipient = self.get_object()
        return self.request.user == recipient.owner

    def handle_no_permissions(self):
        return HttpResponseForbidden("У вас нет прав на это действие.")


def sending_mail(request, pk):
    """Контроллер отправки рассылок. Принимает pk рассылки,
    отправляет согласно списка рассылки, вносит необходимые данные в БД"""
    mail = Mailing.objects.get(pk=pk)
    email_from = settings.EMAIL_HOST_USER
    attempts_list = []
    subject = mail.message.topic
    message = mail.message.text
    owner = mail.owner
    recipients_list = [recipient.email for recipient in mail.recipients.all()]
    for recipient in recipients_list:
        try:
            send_mail(subject, message, email_from, recipient_list=[recipient])
            if mail.status == Mailing.CREATED:
                mail.status = Mailing.ACTIVE
                mail.start_sending = datetime.now()
                mail.save()
            mailing_attempts = MailingAttempts(
                attempt_date=datetime.now(),

mailing/templates/mailing/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet"/> <!--Подключите статические файлы со стилями Bootstrap-->
    .class { padding: 20px 25px; }
</head>
<body>
<header data-bs-theme="dark">
{% include "mailing/includes/menu.html" %}
</header>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    {% if user.is_authenticated %}
    <h1>Привет, {{ user.first_name | default:user.email }}</h1>
    {% else %}
    <h1 class="display-4">Сервис управления рассылками</h1>
    <p class="lead">С.У.Р - это отличный вариант управлять своими рассылками.</p>
    {% endif %}
</div>
{% block content %}
{% endblock %}
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    {% include "mailing/includes/footer.html" %}
</footer>
<script src="{% static '/js/bootstrap.bundle.min.js' %}"></script><!-- Подключите статические файлы со скриптами Bootstrap -->
</body>
</html>

mailing/templates/mailing/finished_mailing_info.html
{% extends 'mailing/base.html' %}
{% block title %}Информирование о завершении рассылки{% endblock %}
{% block content %}
<div class="container">
    <div class="container mt-3">
        <h1 class="mb-4">Информирование об окончании рассылки</h1>
        <h4 class="my-0 font-weight-normal mt-3">Рассылка: {{ mail.message.topic }} - {{mail.status}}</h4>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/home.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block title %}Главная страница{% endblock %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-4 text-center">
            {% if user.is_authenticated %}
            <div class="col">
                <div class="card shadow-sm" >
                    <a class="btn btn-primary" href="{% url 'mailing:message_info' %}" role="button">
                        Управление сообщениям
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm" >
                    <a class="btn btn-primary" href="{% url 'mailing:recipient_info' %}" role="button">
                        Управление получателями рассылок
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm" >
                    <a class="btn btn-primary" href="{% url 'mailing:mailing_info' %}" role="button">
                        Управление рассылками
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm" >
                    <a class="btn btn-primary" href="{% url 'mailing:report_info' %}" role="button">
                        Отчеты по рассылкам
                    </a>
                </div>
            </div>
            {% if perms.user.can_block_users %}
            <div class="col">
                <div class="card shadow-sm" >
                    <a class="btn btn-primary" href="{% url 'users:user_info' %}" role="button">
                        Пользователи сайта
                    </a>
                </div>
            </div>
            {% endif %}
            <div class="col">
                <div class="card shadow-sm" >
                    <a class="btn btn-primary" href="{% url 'users:user_detail' user.pk %}" role="button">
                        Профиль
                    </a>
                </div>
            </div>
            <div class="col">
                <form method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary" role="button">Выход</button>
                </form>
            </div>
            {% else %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-header">
                        <a class="btn btn-primary" href="{% url 'users:login' %}" role="button">Вход</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-header">
                        <a class="btn btn-primary" href="{% url 'users:register' %}" role="button">
                            Зарегистрироваться
                        </a>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block title %}Удаление рассылки{% endblock %}
{% block content %}
<div class="container">
    <div class="col">
        <form class="row" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>Удалить рассылку</h2>
            <p>Вы действительно хотите удалить рассылку "{{ object.message.topic }}"?</p>
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'mailing:mailing_detail' mailing.pk %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}
{% block title %}Детали рассылки{% endblock %}
{% block content %}
<h2 class="mt-2 text-center">Детали рассылки</h2>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-1">
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">Рассылка: "{{ mailing.mailing_name }}"</p>
                        <p class="card-text">Время начала: "{{ mailing.start_sending }}"</p>
                        <p class="card-text">Время окончания: "{{ mailing.end_sending }}"</p>
                        <p class="card-text">Статус: "{{ mailing.status }}"</p>
                        <p class="card-text">Тема сообщения: {{ mailing.message | truncatechars:50 }}</p>
                        <p class="card-text">Владелец: "{{ mailing.owner }}"</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-secondary" href="{% url 'mailing:mailing_list' %}" role="button">
                                    Назад
                                </a>
                                {% if mailing.owner == user %}
                                <a class="btn btn-warning" href="{% url 'mailing:mailing_update' mailing.pk %}"
                                   role="button">
                                    Редактировать
                                </a>
                                <a class="btn btn-danger" href="{% url 'mailing:mailing_delete' mailing.pk %}"
                                   role="button">
                                    Удалить
                                </a>
                                <a class="btn btn-lg btn-block btn-outline-primary"
                                   href="{% url 'mailing:send_mail' mailing.pk %}"
                                   role="button">
                                    Отправить
                                </a>
                                {% endif %}
                                <a class="btn btn-lg btn-block btn-outline-primary"
                                   href="{% url 'mailing:finish_mailing' mailing.pk %}"
                                   role="button">
                                    Завершить
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mailing/base.html' %}
{% block title %}Подробнее о сообщении{% endblock %}
{% block content %}
<h2 class="mt-2 text-center">Детали сообщения</h2>
<div class="container">
    <div class="container mt-3">
        <h4 class="my-0 font-weight-normal mt-3">Сообщение: {{ message.id }}</h4>
        <h4 class="my-0 font-weight-normal mt-3">Тема сообщения: {{message.topic}}</h4>
        <h4 class="my-0 font-weight-normal mt-3">Текст сообщения: {{message.text}}</h4>
        <div class="d-flex justify-content-between align-items-center mt-3">
            <div class="btn-group">
                {% if message.owner == user %}
                <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing:message_update' message.pk %}"
                   role="button">
                    Редактировать
                </a>
                <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing:message_delete' message.pk %}"
                   role="button">
                    Удалить
                </a>
                {% endif %}
                <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing:message_list' %}"
                   role="button">
                    Назад
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_info.html
{% extends 'mailing/base.html' %}
{% block title %}Информация о сообщениях{% endblock %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-4 text-center">
            {% if user.is_authenticated %}
            <div class="col">
                <div class="card shadow-sm" >
                    <a class="btn btn-primary" href="{% url 'mailing:message_list' %}" role="button">
                        Посмотреть список моих сообщений
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <a class="btn btn-primary" href="{% url 'mailing:message_create' %}" role="button">
                        Добавить новое сообщение
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm" >
                    <a class="btn btn-primary" href="{% url 'mailing:home' %}" role="button">
                        На главную
                    </a>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/recipient_form.html
{% extends 'mailing/base.html' %}
{% block title %}Создание/изменение получателя{% endblock %}
{% block content %}
<div class="container">
    <h1 class="mb-4">
        {% if recipient %}
        Форма изменения получателя
        {% else %}
        Форма создания получателя
        {% endif %}
    </h1>
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">
            {% if recipient %}
            Сохранить
            {% else %}
            Создать
            {% endif %}
        </button>
        <a class="btn btn-secondary" href="{% url 'mailing:recipient_info' %}">Отмена</a>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/recipient_info.html
{% extends 'mailing/base.html' %}
{% block title %}Информация по получателям рассылок{% endblock %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-4 text-center">
            {% if user.is_authenticated %}
            <div class="col">
                <div class="card shadow-sm">
                    <a class="btn btn-primary" href="{% url 'mailing:recipient_list' %}" role="button">
                        Список получателей рассылок
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <a class="btn btn-primary" href="{% url 'mailing:recipient_create' %}" role="button">
                        Добавить получателя
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm" >
                    <a class="btn btn-primary" href="{% url 'mailing:home' %}" role="button">
                        На главную
                    </a>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/recipient_list.html
{% extends 'mailing/base.html' %}
{% block title %}Список получателей{% endblock %}
{% block content %}
<h2 class="mt-2 text-center">Список получателей для рассылок</h2>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-4 text-center">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">№</th>
                    <th scope="col">Имя</th>
                    <th scope="col">Электронный адрес</th>
                    <th scope="col">Детали</th>
                </tr>
                </thead>
                <tbody>
                {% for recipient in object_list %}
                <tr>
                    <th scope="row">{{ recipient.id }}</th>
                    <td>{{ recipient.first_name }}</td>
                    <td>{{ recipient.email }}</td>
                    <td><a class="link" href="{% url 'mailing:recipient_detail' recipient.pk %}">Подробнее</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4" class="text-center">Нет получателей для отображения.</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="col">
                <div class="card shadow-sm">
                    <a class="btn btn-primary" href="{% url 'mailing:recipient_info' %}" role="button">Назад</a>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <a class="btn btn-primary" href="{% url 'mailing:home' %}" role="button">На главную</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}