config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.views import (UserRegisterView,  UserInfoView, UserListView, UserDetailsView, UserUpdateView, BlockUserView,
                         UnblockUserView, email_verification, UserForgotPasswordView, UserPasswordResetConfirmView)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="mailing:home"), name="logout"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("user_info/", UserInfoView.as_view(), name="user_info"),
    path("user_list/", cache_page(60)(UserListView.as_view()), name="user_list"),
    path("user/<int:pk>/", UserDetailsView.as_view(), name="user_detail"),
    path("user/<int:pk>/update/", UserUpdateView.as_view(), name="user_update"),
    path("user/<int:pk>/block/", BlockUserView.as_view(), name="user_block"),
    path("user/<int:pk>/unblock/", UnblockUserView.as_view(), name="user_unblock"),
    path("email_confirm/<str:token>/", email_verification, name="email_verification"),
    path("password_reset/", UserForgotPasswordView.as_view(), name="password_reset"),
    path("set_new_password/<uidb64>/<token>/", UserPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """Модель пользователя."""
    username = None
    email = models.EmailField(unique=True, verbose_name="Электронная почта")
    first_name = models.CharField(max_length=50, verbose_name="Имя", blank=True, null=True)
    last_name = models.CharField(max_length=50, verbose_name="Фамилия", blank=True, null=True)
    phone_number = models.CharField(max_length=35, verbose_name="Номер телефона", blank=True, null=True)
    avatar = models.ImageField(
        upload_to="photo/avatars/",
        verbose_name="Аватар",
        blank=True,
        null=True,
        help_text="Загрузите Ваш аватар",
    )
    country = models.CharField(
        max_length=50,
        verbose_name="Стана проживания",
        blank=True,
        null=True
    )
    token = models.CharField(max_length=100, blank=True, null=True, verbose_name="Токен пользователя")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.email}"

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [("can_block_user", "Can block user")]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, SetPasswordForm

from users.models import User


class UserRegisterForm(UserCreationForm):
    """Форма регистрации."""

    class Meta:
        model = User
        fields = ["email", "password1", "password2"]

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите адрес электронной почты"}
        )
        self.fields["password1"].widget.attrs.update({"class": "form-control", "placeholder": "Введите пароль"})
        self.fields["password2"].widget.attrs.update({"class": "form-control", "placeholder": "Введите пароль"})

    def clean_email_address(self):
        """Проверка электронной почты."""
        email_address = self.cleaned_data.get("email")
        if User.objects.filter(email=email_address).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("Этот адрес электронной почты уже зарегистрирован!")
        return email_address


class UserForm(forms.ModelForm):
    """Форма обновления данных."""

    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "phone_number", "avatar", "country")

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите адрес электронной почты"}
        )
        self.fields["first_name"].widget.attrs.update({"class": "form-control", "placeholder": "Введите имя"})
        self.fields["last_name"].widget.attrs.update({"class": "form-control", "placeholder": "Введите фамилию"})
        self.fields["phone_number"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите номер телефона"}
        )
        self.fields["avatar"].widget.attrs.update({"class": "form-control", "placeholder": "Загрузите фотографию"})
        self.fields["country"].widget.attrs.update({"class": "form-control", "placeholder": "Введите страну проживания"})

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get("phone_number")
        if phone_number and not phone_number.isdigit():
            raise forms.ValidationError("Номер телефона должен содержать только цифры.")
        return phone_number

    def clean_email_address(self):
        email_address = self.cleaned_data.get("email")
        if User.objects.filter(email=email_address).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("Этот адрес электронной почты уже зарегистрирован!")
        return email_address


class UserForgotPasswordForm(PasswordResetForm):
    """Запрос на восстановление пароля."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control", "autocomplete": "off"})


class UserSetNewPasswordForm(SetPasswordForm):
    """Изменение пароля после подтверждения."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control", "autocomplete": "off"})

users/views.py
import secrets

from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, ListView, View, TemplateView
from django.views.generic.edit import CreateView, UpdateView

from users.forms import UserRegisterForm, UserForm, UserForgotPasswordForm, UserSetNewPasswordForm
from users.models import User


class UserInfoView(TemplateView):
    """Контролер представления страницы с информацией о пользователях."""
    template_name = "users/user_info.html"


class UserRegisterView(CreateView):
    """Контроллер регистрации профиля."""
    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email_confirm/{token}/"
        send_mail(
            subject="Подтверждение регистрации.",
            message=f"Для активации Вашего аккаунта перейдите по ссылке: {url}",
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email,],
        )
        return super().form_valid(form)


def email_verification(request, token):
    """Контроллер верификации почты."""
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class UserListView(LoginRequiredMixin, ListView):
    """Контроллер отображения списка пользователей сервиса."""
    model = User
    template_name = "users/user_list.html"


class UserDetailsView(DetailView):
    """Контроллер отображения профиля пользователя."""
    model = User
    template_name = "users/user_detail.html"


class UserUpdateView(UpdateView):
    """Контроллер обновления профиля пользователя."""
    model = User
    form_class = UserForm
    template_name = "users/user_form.html"
    success_url = reverse_lazy("mailing:home")


class UserForgotPasswordView(SuccessMessageMixin, PasswordResetView):
    """Контроллер по сбросу пароля по почте."""
    form_class = UserForgotPasswordForm
    template_name = "users/user_password_reset.html"
    success_url = reverse_lazy("mailing:home")
    success_message = "Письмо с инструкцией по восстановлению пароля отправлена на ваш email."
    email_template_name = "users/password_reset_mail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Запрос на восстановление пароля."
        return context


class UserPasswordResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    """Контроллер установки нового пароля."""
    form_class = UserSetNewPasswordForm
    template_name = "users/user_password_set_new.html"
    success_url = reverse_lazy("mailing:home")
    success_message = "Пароль успешно изменен. Можете авторизоваться на сайте."

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Установить новый пароль."
        return context


class BlockUserView(LoginRequiredMixin, View):
    """Контроллер блокировки пользователей сайта."""
    def post(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        if not request.user.has_perm("can_block_user"):
            return HttpResponseForbidden("У вас нет прав на это действие.")

        user.is_active = False
        user.save()
        return redirect("users:user_list")


class UnblockUserView(LoginRequiredMixin, View):
    """Контроллер разблокировки пользователей сайта."""
    def post(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        if not request.user.has_perm("can_block_user"):
            return HttpResponseForbidden("У вас нет прав на это действие.")

        user.is_active = True
        user.save()
        return redirect("users:user_list")

users/templates/users/login.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block title %}Вход на сайт{% endblock %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <h2 class="mb-4">Вход на сайт</h2>
        <div class="col-4">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Войти</button>
                        <a class="btn btn-primary" href="{% url 'users:password_reset' %}" role="button">
                            Восстановить пароль
                        </a>
                        <a class="btn btn-primary" href="{% url 'mailing:home' %}">Отмена</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_mail.html
{% autoescape off %}

Вы получили это электронное письмо, потому что запросили сброс пароля для своей учетной записи пользователя на {{ site_name }}.

Перейдите на следующую страницу и выберите новый пароль:
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
Ваше имя пользователя, если вы забыли: {{ user.get_username }}

Спасибо за использование нашего сайта!

The {{ site_name }} team

{% endautoescape %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block title %}Регистрация на сайте{% endblock %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <h2 class="mb-4">Регистрация</h2>
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                        <a class="btn btn-primary" href="{% url 'mailing:home' %}">Отмена</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block title %}Мой профиль{% endblock %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-1">
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <img src="{{ object.avatar | media_filter }}" width="100%" height="250">
                        <h4 class="my-0 font-weight-normal mt-3">Электронная почта: {{ object.email }}</h4>
                        <h4 class="my-0 font-weight-normal mt-3">Имя: {{ object.first_name }}</h4>
                        <h4 class="my-0 font-weight-normal mt-3">Фамилия: {{ object.last_name }}</h4>
                        <h4 class="my-0 font-weight-normal mt-3">Телефон: {{ object.phone_number | default:"не указан" }}</h4>
                        <h4 class="my-0 font-weight-normal mt-3">Страна: {{ object.country | default:"не указана" }}</h4>
                        <h4 class="my-0 font-weight-normal mt-3">Дата регистрации: {{ object.date_joined }}</h4>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-secondary" href="{% url 'users:user_info' %}" role="button">Назад</a>
                                <a class="btn btn-secondary" href="{% url 'users:user_update' user.pk %}" role="button">
                                    Редактировать
                                </a>
                                {% if user.is_active %}
                                <form action="{% url 'users:user_block' user.pk %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-secondary" role="button" type="submit">
                                        Заблокировать пользователя
                                    </button>
                                </form>
                                {% else %}
                                <form action="{% url 'users:user_unblock' user.pk %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-secondary" role="button" type="submit">
                                        Разблокировать пользователя
                                    </button>
                                </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block title %}Редактирование профиля{% endblock %}
{% block content %}
<div class="container">
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">
            Сохранить
        </button>
        <a class="btn btn-secondary" href="{% url 'users:user_detail' user.pk %}">Отмена</a>
    </form>
</div>
{% endblock %}

users/templates/users/user_info.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block title %}Информация о пользователях{% endblock %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-4 text-center">
            {% if user.is_authenticated %}
            <div class="col">
                <div class="card shadow-sm" >
                    <a class="btn btn-primary" href="{% url 'users:user_list' %}" role="button">
                        Список пользователей
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm" >
                    <a class="btn btn-primary" href="{% url 'mailing:home' %}" role="button">
                        На главную
                    </a>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block title %}Страница пользователей{% endblock %}
{% block content %}
<h2 class="mt-2 text-center">Список пользователей</h2>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-4 text-center">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">№</th>
                    <th scope="col">Имя</th>
                    <th scope="col">Электронный адрес</th>
                    <th scope="col">Детали</th>
                </tr>
                </thead>
                <tbody>
                {% for user in object_list %}
                <tr>
                    <th scope="row">{{ user.id }}</th>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.email }}</td>
                    <td><a class="link" href="{% url 'users:user_detail' user.pk %}">Подробнее</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4" class="text-center">Нет пользователей для отображения.</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="col">
                <div class="card shadow-sm">
                    <a class="btn btn-primary" href="{% url 'users:user_info' %}" role="button">Назад</a>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <a class="btn btn-primary" href="{% url 'mailing:home' %}" role="button">На главную</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_password_reset.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
<div class="card mb-3 border-0 nth-shadow">
    <div class="card-body">
        <div class="card-title nth-card-title">
            <h4>Запрос на восстановление пароля на сайте</h4>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-dark mt-2" type="submit">Восстановить пароль</button>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/user_password_set_new.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block title %}Установка нового пароля{% endblock %}
{% block content %}
<div class="card mb-3 border-0 nth-shadow">
    <div class="card-body">
        <div class="card-title nth-card-title">
            <h4>Установить новый пароль</h4>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-dark mt-2" type="submit">Подтвердить</button>
        </form>
    </div>
</div>
{% endblock %}